#!/bin/bash

sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f0_S0.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f0_S2.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f0_S4.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f0_S8.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f0_S16.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f0_S32.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f1_S0.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f1_S2.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f1_S4.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f1_S8.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f1_S16.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f1_S32.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f2_S0.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f2_S2.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f2_S4.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f2_S8.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f2_S16.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f2_S32.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f3_S0.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f3_S2.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f3_S4.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f3_S8.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f3_S16.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f3_S32.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f4_S0.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f4_S2.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f4_S4.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f4_S8.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f4_S16.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f4_S32.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f5_S0.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f5_S2.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f5_S4.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f5_S8.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f5_S16.sh
sbatch /home/coneill/sync/code/pinns_data_assimilation/slurm/mazi_fixed_grid/test/t10_f2/mfg_t10f2_j1_f5_S32.sh
